### ISSUE TITLE
Open source this scraper

### ISSUE THREAD

**Issue by frankgo81** [tugkan/walmart-scraper#2]
It would be great if you could open source this actor like Amazon did and Aliexpress

https://apify.com/tugkan/aliexpress-scraper/source-code

https://apify.com/vaclavrut/amazon-crawler/source-code

Thanks.

**Comment by tugkan** [comment]
Hey @frankgo81 . Unfortunately for now there is no plan to open source this project because it's a paid actor. 

Bet.
